[package]
name = "ray-tracing"
version = "0.1.0"
authors = ["Milan Tichavský <milantichavsky@seznam.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8"
image = "0.23.10"
log = "0.4"
rand = "0.8"